<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-7HPDDDR" failures="1" tests="3" name="DemoTestNG" time="1.172" errors="0" timestamp="2022-10-11T23:48:53 IST">
  <testcase classname="Automation.TestNG" name="Test3" time="1.023">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method Automation.TestNG.Test3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Automation.TestNG.Test3() didn't finish within the time-out 1000
at java.base@18.0.2/java.lang.Thread.sleep(Native Method)
at app//Automation.TestNG.Test3(TestNG.java:60)
at java.base@18.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800d0a800.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.2/java.lang.invoke.LambdaForm$MH/0x0000000800d0b000.invoke(LambdaForm$MH)
at java.base@18.0.2/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.2/java.lang.Thread.run(Thread.java:833)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="Automation.TestNG" name="Test2" time="0.006"/>
  <testcase classname="Automation.TestNG" name="test4" time="0.0">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="Automation.TestNG" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- DemoTestNG -->
